spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: patients
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include: "*"
#  tracing:
#    sampling:
#      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: http://zipkin:9411/api/v2/spans
