server:
  port: 8087
  shutdown: graceful

spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: prescription
      username: root
      password: rootpass
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8081/realms/medical-records
          jwk-set-uri: http://keycloak:8081/realms/medical-records/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    hostname: discovery-server
    instance-id: ${spring.application.name}:${instanceId:${random.value}}

  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
