server:
  port: 8087
  shutdown: graceful

spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: prescription
      username: root
      password: rootpass
      authentication-database: admin
#    redis:
#      host: redis
#      port: 6379
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://keycloak:8081/realms/medical-records
#          jwk-set-uri: http://keycloak:8081/realms/medical-records/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  instance:
    hostname: prescription-service
    instance-id: ${spring.application.name}:${instanceId:${random.value}}

  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

doctor:
  service:
    url: http://doctor-service:8084
patient:
  service:
    url: http://patient-service:8086
visit:
  service:
    url: http://visit-service:8088
