server:
  port: 8087
  shutdown: graceful

spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: prescription
      username: root
      password: rootpass
      authentication-database: admin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${instanceId:${random.value}}

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

doctor:
  service:
    url: http://localhost:8084
patient:
  service:
    url: http://localhost:8086
visit:
  service:
    url: http://localhost:8088
