spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://config-server:8087/
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: "http://localhost:9098/realms/medical-records"